version: '3.4'

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

networks:
  subnet_0:
    driver: bridge

volumes:
  mysql-data: {}

secrets: {}

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.30-debian
    ports:
      - '3306:3306'
      - '33060:33060'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS:-admin}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-events}
      TZ: 'America/Sao_Paulo'
    networks:
      - subnet_0
    restart: on-failure
    volumes:
      - mysql-data:/var/lib/mysql
    logging: *logging

  redis:
    container_name: redis
    hostname: redis
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379
    networks:
      - subnet_0
    restart: on-failure
    logging: *logging

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - subnet_0
    restart: on-failure
    logging: *logging
